config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :products, only: [:index, :show]

root 'products#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
	@products_list = Product.all
  	@products = Product.order('created_at DESC')
	  respond_to do |format|
	    format.html
	     format.xlsx {
	    	response.headers['Content-Disposition'] = 'attachment; filename="all_products.xlsx"'
	  		}
	  end
	end

	def show
	  @product = Product.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Axlsx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>List of products</h1>
<%= link_to 'Download as .xlsx', products_path(format: :xlsx) %><hr>
<%  @products_list.each do |c| %>
	<p>
	Product: <b><%= c.title %></b><br>
	Price: $<b><%= c.price%></b><br>
	</p>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p>Price: <%= @product.price %></p>